### ISSUE TITLE
[Services] Allow @Service on @Produces

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#10]
- **For**
    - Symmetry with `@Reference` bridge producers
    - Needed when OSGi-fying third party code
    - E.g. expose a Mina SSHD
        ```
        @Produces
        @Service
        public org.apache.sshd.SshServer makeServer(@Configuration @Port int port) {
            ...
        }
        ```
- **Against**
    - ?

**Comment by rotty3000** [comment]
This sounds dangerous...

**Comment by pkriens** [comment]
Why would it be dangerous? I think this is expected to work by a CDI user? It is one of the main improvements that allows you to pick an implementation type for a service?

**Comment by rinswind** [comment]
The code above is close to a real use case where I used a similar feature of Blueprint.
It is a very compelling feature of CDI to use producer fields and methods as equals to beans.

**Comment by rotty3000** [comment]
Producers are triggered much more as side effects... but if you think we can manage the lifecycles of those then... I guess I'm ok with it.

**Comment by rinswind** [comment]
We have to code something up to be completely sure.
Closing this for now with the resolution that we will support it.
This makes #7 more relevant.

**Comment by rotty3000** [comment]
I've added to the possible target types to make this possible.
