### ISSUE TITLE
[References] Should @Bundle, @Prototype, @Greedy, @PID, @FactoryPID be qualifiers?

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#13]
- In fact only `@Reference` and `@Configuration` are qualifiers
- This means these are the same:
    `@Reference Hello hello;`
    `@Reference @Greedy Hello otherHello;`
    `@Reference @Greedy @Bundle Hello anotherHello;`
- More importantly these are the same
    `@Configuration @PID("org.example.hello") Map<String, ?> props;`
    `@Configuration @PID("org.example.another.hello") Map<String, ?> props;`

**Comment by rotty3000** [comment]
See the current API.

**Comment by pkriens** [comment]
Since we create the synthetic bean I assume all these examples are wired to different beans?

**Comment by rinswind** [comment]
@pkriens It is up to the implementation to decide how to map the injection points to beans. One synthetic bean can have enough qualifiers to satisfy many injection points. E.g. when one service is imported make one bean for it, then add the qualifiers of all `@Inject @Reference`.

In all cases things we deem different must have qualifiers to separate the injection points. I'd `@PID` obviously needs to be a qualifier. I am not so sure about the others, but it may be better to err on the safe side.

**Comment by rinswind** [comment]
Closing the issue after the latest API update by @rotty3000
