### ISSUE TITLE
[Events] Clarify AddingEvent state

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#14]
- **Suggestion**
    - Each method call to an observer gets a new `AddingEvent`
    - After the call ends all methods of that `AddingEvent` throw `IllegalStateException`
    - The `AddingEvent.getService()`, `AddingEvent.getServiceProperties()` return a snapshot
        - I.e. repeated calls return the same result

**Comment by rotty3000** [comment]
See the current API which has overloaded methods with consumers for all the types. Do we really need to re-pack the event? I don't think we need it.

**Comment by pkriens** [comment]
I do not think it is a good idea to throw exceptions. However, an event should imho be defined to hold the state when called. I.e. it must be immutable.

**Comment by rinswind** [comment]
The CDI SPI does this for it's events so it seemed like a best practice:
https://docs.jboss.org/cdi/api/2.0/javax/enterprise/inject/spi/ProcessBean.html#getBean--

Are you really sure it is OK for the users to leak the event object out of the observer into any random code that may have any random lifecycle?

**Comment by pkriens** [comment]
I think you set yourself up for all kind of race conditions. I do not see why exceptions help as long as the object is immutable? I.e. now you can pass it to an executor to process in order but that would run into problems? Seems overly aggressive to me ...

**Comment by rinswind** [comment]
But `AddingEvent<T>` is mutable by design. You can attach callbacks to it. 

Also methods like `getServiceProperties()` I assume will return the current state so at the very least the object is not "deeply immutable".

**Comment by rotty3000** [comment]
so I propose: 
* that we remove the "getter" methods completely
* that we add a subscriber methods for "adding" event
* that we rename the class, but to what exactly I'm not sure

```
	/**
	 * Subscribe an action to the "adding" service event.
	 *
	 * @param action to subscribe to the "adding" service event
	 */
	void onAdding(Runnable action);

	/**
	 * Subscribe an action to the "adding" service event.
	 *
	 * @param action to subscribe to the "adding" service event
	 */
	void onAdding(Consumer<S> action);

	/**
	 * Subscribe an action to the "adding" service event.
	 *
	 * @param consumer to subscribe to the "adding" service event
	 */
	void onAddingServiceReference(Consumer<ServiceReference<S>> consumer);

	/**
	 * Subscribe an action to the "adding" service event.
	 *
	 * @param consumer to subscribe to the "adding" service event
	 */
	void onAddingServiceObjects(Consumer<ReferenceServiceObjects<S>> consumer);

	/**
	 * Subscribe an action to the "adding" service event.
	 *
	 * @param consumer to subscribe to the "adding" service event
	 */
	void onAddingProperties(Consumer<Map<String, ?>> consumer);
```

**Comment by rotty3000** [comment]
Also, I found this interesting bit of information in [10.4.1](http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#observer_method_event_parameter):
> Modifications made to the event parameter in an observer method are propagated to following observers. The container is not required to guarantee a consistent state for an event parameter modified by asynchronous observers.

**Comment by rotty3000** [comment]
Now what you may notice from that section is that CDI supports async events. So we need to decide if the events we are going to be sending are `async` or `sync`. 

I'm leaning toward `sync`! but welcome other opinions.

**Comment by rinswind** [comment]
Let's decide on sync/async at #42 (I am for sync)

**Comment by rinswind** [comment]
Without 
`S AddingEvent.getService()`
the runnable version doesn't make much sense
`AddingEvent.onAdding(Runnable)`

Rarely someone is interested on just reacting. They want to do something with the service.
So if we go that way we should leave only the `Consumer` flavor.

**Comment by rinswind** [comment]
> that we rename the class, but to what exactly I'm not sure

In #16 we already proposed simply `ReferenceEvent`

**Comment by rinswind** [comment]
@rotty3000 Still why can't we make `AddingEvent` work like the CDI SPI events?

They are highly mutable and give access to the container internals in dangerous ways, but are only valid during the event call. Then `AddingEvent` doesn't need to change that much. Just be invalidated in a thread safe manner.

**Comment by rotty3000** [comment]
so
# Suggestion
- rename to `ReferenceEvent`
- make the event invalid outside the observer (`throws IllegalStateException`)
- remove the getters
- add the `adding` methods
- remove the `Runnable` methods

**Comment by rotty3000** [comment]
I'm going to proceed like this for now.

**Comment by rotty3000** [comment]
updated the javadoc
