### ISSUE TITLE
[Events] Allow optional @Reference on AddingEvent

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#15]
- **For**
    - The user may need an escape hatch for the reference type
    - Symmetry with field injection
- **Against**
    - ?

**Comment by rotty3000** [comment]
There's no need for "escape hatch" on type, because `<S>` is always the service type. Not sure why they need another mechanism.

I think we should omit the need for `@Reference` on the events.

**Comment by rinswind** [comment]
I assumed this had useful meaning:
`@Inject @Reference(Something.class) AnotherThing thing;`
Therefore the same must have meaning for events.
Is the `Class<?> value()` on `@Reference` added only to support injections of `Map<String, ?>`?

**Comment by rotty3000** [comment]
> I assumed this had useful meaning:
> @Inject @Reference(Something.class) AnotherThing thing;

It does, it's narrowing the possible types to `Something` which must be "assignable to" `AnotherThing`.

> Therefore the same must have meaning for events.

I don't disagree! Ok, then I'll agree on that @Reference be optional on the event.

> Is the Class<?> value() on @Reference added only to support injections of Map<String, ?>?

No, it's also for narrowing.

**Comment by rinswind** [comment]
Closing this with the resolution:

`@Reference` is optional on `AddingEvent<S>` with the **same semantics** as on a regular injection point: Narrow the service type `S`.
