### ISSUE TITLE
[Property Annotations] Should all component property annotations be qualifiers?

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#18]
- **For**
    - Inject individual configuration elements.
    - Like DS lets us put property type instances in activation methods.
    - E.g.
        `@Inject @Configuration @Port port;`
        `@Inject @Configuration @PID("org.server.connector") Port port;`
- **Against**
    - Can cause unintended dependency injection binding
- **Suggestion**
    - Regular annotations by default
    - If the user wants they can make their own qualifiers.
        - Hopefully the main use case is for user annotations like the one above, rather than for third party annotations.

**Comment by rotty3000** [comment]
Configuration types don't have to be qualifiers for the purpose of binding, just annotations.
Also it would be:
`@Inject @Configuration Port port;` and not `@Inject @Configuration @Port port;`

**Comment by rinswind** [comment]
Closing with resolution: yes
