### ISSUE TITLE
[Property Annotations] What to do with repeated property annotations?

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#19]
- **Suggestion**
    - On `@Component`: merge into a list property
    - On `@Reference`: expand to an `(|(key=val-1)...(key=val-N))`

**Comment by rotty3000** [comment]
* On `@Component`: merge to array as DS does.
* On `@Reference`: following the logic of qualifiers, they are AND (&). I suggest we follow the same.

**Comment by rinswind** [comment]
Agreed on the array

As for the `&` will it not be the case that this will almost always make filters that are impossible to satisfy?
```
@interface Port {
    int value();
}

@Reference @Port(80) @Port(8080) Connector connector;
```
Or we just let the users shoot themselves in the foot, but keep the rules simple?

**Comment by rotty3000** [comment]
Please review the CDI spec w.r.t. repeatable annotations. It says exactly this! So, don't do that and you will be fine.

The thing is:
1. don't over specify using qualifiers
2. if you need complex filter, use @Filter

**Comment by rinswind** [comment]
Closing this with the resolution: 
- On `@Component` merge into an array
- On `@Reference` no special treatment: add (&...) per qualifier

**Comment by rinswind** [comment]
For reference: https://issues.jboss.org/browse/CDI-471

**Comment by rotty3000** [comment]
action required

**Comment by rotty3000** [comment]
closing as added to spec draft, continue on bugzilla
