### ISSUE TITLE
[Property Annotations] What to do with property annotations with more than one attribute?

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#20]
- **Note** Can't find anything in the DS spec on the subject
- **Suggestion**
    - Any qualifier that has a `value()` attribute with an OSGi filter compatible type is used
    - All other attributes are ignored
        - Can be used for special processing by the extender similar to the requirement directives:
            - E.g. `@RequireRole("administrator")`
            - ...but `@RequireRole(value="administrator", onFailThrow=UnauthenticatedException.class)`
            - This can be handled by a security extension that supports a specification where a property `require.role` is defined.

**Comment by rotty3000** [comment]
This is defined by component property types. I'm suggesting we just adopt that and that was my intention all along. Also we already discussed how to leverage existing "standard" component property types.

**Comment by rinswind** [comment]
I agree.
I am confused what happens in these cases:
```
@interface Pair {
    String one();
    String two();
}

@Pair @Reference Hello hello;

// What does this add?
// "one" and "two"
// "pair.one" and "pair.two" to separate them from they keys in e.g. @AnotherConfiguration
@Component
@Pair
class Hello {
}
```

**Comment by rotty3000** [comment]
properties on @Reference are ALWAYS AND'd (&)

properties on @Component are just merged as properties are. The rules for component property types define how they are converted to properties. it's too complex to write all here. But it's already written in the spec (Converter and DS)

**Comment by rinswind** [comment]
> properties on @reference are ALWAYS AND'd (&)
So it's going to be `(&(one=1)(two=2))`?
More generally are you saying that all properties are merged into one and then each key is added as `(&(key=val))`?

**Comment by rotty3000** [comment]
... on `@Reference`, yes! What else could you possibly do?

Again, this is exactly how @Qualifiers work! *All* qualifiers must match to get a result.

**Comment by rinswind** [comment]
Closing this with the resolution:

- All qualifiers are converted into a `Map` by the rules in the DS spec.
- All `Map`s are merged.
- On `@Component` the merger is further added to the component properties
- On `@Reference` the merger is converted into an `(&(key=val)...(key=val))` expression and added to the target filter.

Basically qualifiers that serve as configuration holders can freely be used as with references to build target filters.
