### ISSUE TITLE
[Components] @ComponentScoped must fire @Initialized, @BeforeDestroy, @Destoyed events

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#21]
- **For**
    - It is recommended by Weld and/or the CDI spec
    - Just require in the specification that these are fired.
- **Against**
    - ?

**Comment by rotty3000** [comment]
Agreed! I already had that on my TODO.

**Comment by rinswind** [comment]
Closing the issue

**Comment by rotty3000** [comment]
I'm just reopening to indicate that some action on this is required.

**Comment by rotty3000** [comment]
closing as added to the spec draft

we can debate further on bugzilla
