### ISSUE TITLE
[DTOs] Should LifecycleTemplateDTO be added?

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#22]
It is confusing that on the template side there is `ComponentTemplateDTO` but on the runtime side there is  `LifecycleDTO` and a `ComponentDTO` that relate to one `ComponentTemplateDTO`.
Adding a mirror `LifecycleTemplateDTO` will make things symmetrical.

**Comment by rotty3000** [comment]
Can we close this in favour of the new DTO models being proposed?

**Comment by rinswind** [comment]
This is about extending my existing model with another DTO.
It may become irrelevant later.

**Comment by rinswind** [comment]
We have renamed the DTOs so that it is pretty clear what goes where.
I.e. we have `ComponentDTO` and a mirror `ComponentTemplateDTO`. Then we have a runtime-only `ComponentInstanceDTO`. It is clear enough that there should not be a mirror `ComponentInstanceTemplateDTO`.

Closing the issue
