### ISSUE TITLE
[Configuration] Inject individual configuration properties

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#26]
- **For**
    - Fits dependency injection
        - Multiple objects support a service
        - Each consumes parts of the service configuration
        - Easy to test without making configuration annotation literals
    - Symmetry with DS
- **Against**
    - Can be worked around with producers
        ```
        @Produces @ComponentScoped @Port
        public int getPort(@Configuration @PID("org.example.connector") Map<String, ?> config) {
            return (int) config.get("port");
        }
        ...
        @Inject @Port int port;
        ```      
- **Suggestion**
    - When
        `@Inject @Configuration @APropertyAnnotation String aPlainTypeConversion;`
    - Make a synthetic bean to support the injection that uses the converter on key "a.user.qualifier" to String.
    - Symmetry with `@Reference` that also allows property annotations

**Comment by rotty3000** [comment]
Why? This is no better than defining an annotation to provide a single member value over the properties. Plus you get a default value when there is no configuration, or specified property. I don't think this is necessary when you have this very elegant option:

```
@interface Config {
   String my_property() default "blue";
}

@Inject Config config;
```

**Comment by rotty3000** [comment]
Furthermore, I don't see any symmetry with DS in your explanation.

**Comment by pkriens** [comment]
I agree, let's not go there

**Comment by rinswind** [comment]
@rotty3000 I am sorry. That "symmetry with DS" must have slipped in during the issue dump.

Still the annotation instance approach forces me to make my own annotation literals to test.

I will close this since the producer workaround is not so painful, we better keep the first release simple.
