### ISSUE TITLE
[Components] @Named vs Bean.getName() for synthetic beans

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#28]
- **Issue**
    - A synthetic bean can have an `@Named` qualifier and a different `Bean.getName()`
    - At the same time two beans with the same `Bean.getName()` can't exist in the same container
    - Should the spec say anything about this?
- **Suggestion**
    - Don't say anything

**Comment by rotty3000** [comment]
Synthetic beans are implementation details. As such the naming doesn't outwardly matter. The names here are not intended to be used by EL (which is what @Named is generally used for). The goal of "reference" names is to be able to target them with configuration. that's all. So, as far as I can tell, there's no reason to specify anything here. As long as configuration can be targeted to a particular `@Reference` implement the naming however you like.

**Comment by pkriens** [comment]
Hmm. This implies you could never explicitly reference a service from EL?

**Comment by rotty3000** [comment]
I don't think this should even be a requirement. Why not make the bean that holds the reference "named" and refer to that in EL instead. I don't see that there's a strong reason to touch any synthetic beans from EL directly. I'm not saying that implementation can't support this... I just don't think it should be a requirement.

**Comment by pkriens** [comment]
You are probably right. The injectionpoint is needed regardless so EL could refer to that IP's bean. 

Still a bit of a nagging feeling that EL should be able to refer to a service directly. However, this seems impossible because you need to know the dependency and that info is not available for EL scripts. Guess no easy solution so lets close this.

**Comment by rinswind** [comment]
Closing
