### ISSUE TITLE
[Components] Use property annotations for OSGi property-like setup instead of special annotations

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#29]
**Note** This is controversial and I am posting it here, because I could't explain it well over the chat. Something useful may come out.
 
# Line of reasoning
1. What happens when a user `@ServiceScope` is added to `@Reference`?
    - I.e. conflicts with `@Prototype` and `@Bundle`
2. What if instead of definition error:
    1. Allow it
    2. Extender will automatically work with anything that yields `service.scope=(singleton | prototype | bundle)`
3. If this works then 
    1. Better to remove `@Prototype` and `@Bundle`
    2. Add a standard `@ServiceScope` for those who want it
4. But `@Prototype/Bundle` is needed on `@Service`
5. Use the `@ServiceScope` on `@Component` too
    1. The extender blindly converts property annotations to component configuration
    2. Later the extender has special processing for a configuration property `service.scope`
        - Including removing it since it may be converted to ActivatinoModelDTO.scope
6. Run with the approach to see where it leads

# Suggestion
## Split the annotations to
- Core structural/behavioral:
    - `@Component`, `@Service`, `@Reference`, `@Greedy`, `@Configuration`
- Tuneup property annotations applied to the core set:
    - Use for anything that appears in referenced OSGi spec as a property
    - Even if user can't set it but later can see it:
        - E.g. `service.scope` on service can't be set directly.
        - .. depends on e.g. registering `PrototypeServiceFactory`    
        - ...but later the user can see it as a service registration property
    - Some reserved property name+value type induce custom behavior from the extender.
    - Remove the specialized annotations:  I.e.  `@PID`, `@FactoryPID`

## The extender has very simple algorithm to build the model
- The core annotations determine the main model structure: `ComponentModelDTO`, `ReferenceModelDTO`, `ActivationModelDTO`, etc.
- Everything else is processed by common rules for property annotations
    - .. and added to the appropriate place in the core structure
- Once the model is built the extender does post-processing
    - Based on reserved property names (e.g. `service.scope`) and compatible values
- To add more ways to configure just allow more sites for property annotations
    - E.g. when used on a TYPE_USE site and has a "Class<> value()" the Class of the type is used
        `class HelloImpl implements @Objectclass Hello`
- When the property name is not intuitive the meta annotation can define an override
    - `@Objectclass` can become `@ServiceType` if meta-annotated with `@PropertyType("objectclass")`

## Suggested properties
- `@ServiceScope`, `@ServiceRanking`, `@ServicePid`, `@ServiceFactorypid`, `@Objectclass`
- Where `@ServiceScope`
    - Has an `enum ServiceScope.Value {Singleton, Bundle, Prototype}`
    - Applicable to class, field, parameter
    - Where `@ServiceScope` on class leads to `objectclass=<all implemented interfaces>`
        - And can be overridden with `@Objectclass`
- Where `@ServicePid`
    - Is repeatable
    - Applicable to class
    - Has additional "directive" member `@Nonbinding boolean required() default false;`
- Where `@Objectclass` is repeatable with member `Class<?> value(); // No default`
    - On `@Reference` can add validation that it's compatible with the injection point type
- Remove `@Service`, `@Bundle`, `@Prototype`, `@PID`, `@FactoryPID`

**Comment by rotty3000** [comment]
This has way too much detail. I can't comment on anything. Can you break it down into smaller parts?

**Comment by rotty3000** [comment]
Is this issue still relevant in the fast of the direction of @Qualifier ?

**Comment by rinswind** [comment]
Probably yes.
But it's a radial restructuring of the spec. We don't have time to decide on this.
Can we say instead that we will let the user shoot themselves in the foot if they decide to put their custom `@ServiceScope` qualifier on `@Reference` and/or `@Service`? Which would conflict with our special `@Bundle` and `@Prototype`?

**Comment by rotty3000** [comment]
1) any property `service.scope` cannot collide on `@Service`, because any such property is ignored by the service registry.
2) if the user adds a `@ServiceScope` qualifier to override then I think we should allow it.. but they may have both `@Prototype` and `@ServiceScope(BUNDLE)` and then we have a problem. I think we should always let `@Prototype` win in this case.

**Comment by rinswind** [comment]
We can document on `@Prototype` and `@Bundle` that they set `service.scope` last before the service is registered and override anything else.

**Comment by rotty3000** [comment]
there's nothing to spec here since `service.scope` as a service property is ignored by the service registry.

Regarding `@Bundle` and `@Prototype` I've got those in the spec doc already.

closing, we can debate further on bugzilla.
