### ISSUE TITLE
[Runtime] Communicate change via  "service.changecount"

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#31]
**Suggestion**
- Remove `CdiEvent` and `CdiContainerState`
- Communicate changes via updates to `service.changecount` on `CdiContainer`
    - The users must (re)inspect the DTOs to determine what has changed
- Communicate changes via updates to `service.changecount` on `CdiRuntime`
    - Should the runtime communicate only coarse-grained changes like add/remove of a bundle
    - ... or also changes within each container

**Note**
The state machine for containers is removed. The users can inspect the "runtime" set of DTOs to determine what is the state of the container, application, a component. This is the simpler option given the nested nature of the container.

**Comment by rotty3000** [comment]
The `service.changecount` does not represent the state of the container. That only comes into play once the contaier is completely statically satisfied and then dynamic things happen. The container state tells you at what stage the container is at.

Furthermore, I already added CdiContainerState to the ContainerDTO.

**Comment by rinswind** [comment]
The `service.changecount` prompts interested parties to (re)inspect the DTOs.

The DTOs have all the information captured in the sate but in a different form. 
- E.g. `ExtensionDTO` carries information whether the extension is there or not.
- E.g. the `ConfigurationDTO` for the application component carries similar information.

I propose that we remove the state machine because:
- There is no single entity the states refer to:
    - `waiting_for_extensions` is about the `ContainerDTO`
    - `waiting_for_configurations` is about the root `ComponentLifecyceDTO`
    - `waiting_for_references` is about the root `ComponentDTO`
    - `satisfied` is about the root `ActivationDTO`s starting, but also about the child `ComponentLifecycleDTO`s starting to track configurations.
- It is confusing to not have similar state machines for the child components, but we have not added them.

The `CdiContainer` service must be registered as soon as the extender touches the bundle, not when everything is ready to run. From that point on anything that happens must be communicated through `CdiContainer`, `service.changecount` and the DTOs. Even the we fail with a definition error the `CdiContainer` must remain registered and hold the error for inspection.

Should we try to split this into two issues?
- Lifecycle of `CdiContainer`
- Proposal to remove the state machine and use `service.changecount`

**Comment by rinswind** [comment]
I like to have a way to know what is happening with the CDI bundle by just inspecting the service from the console. But these states don't match the current abstract structure (I.e. Peter's design)

**Comment by rotty3000** [comment]
Perhaps you're right... but experience shows me that inspecting DTOs as an event observer is painful.

**Comment by pkriens** [comment]
I tihnk we need a call to go to my findings with the DTOs. The current design I think has too many classes

**Comment by rinswind** [comment]
Closing this with resolution:
- Remove `CdiEvent` and `CdiContainerState`
    - An additional argument is that the state machine constraints the possible implementations too much. Blueprint provides an example of this.
- By implication remove the state machine
- Communicate change via `service.changecount`
