### ISSUE TITLE
[Components] Provide a way to describe the Application component in code

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#32]
**For**
- The users are unlikely to use the application component to code simple bundles unless they can configure it via annotations.

**Against**
- A simple bundle can be coded with one `@Component` bean.

**Suggestion (Tentative)**
- Allow multiple `@PID` on exactly one `@ApplicationScoped` bean per bundle.
- Maybe if the bean is `@Named` use the name as container Id as well.

**Comment by rotty3000** [comment]
Can we do this in a later version of the spec? What's the difference here to include the PIDs in the requirement in the manifest? I would like to not do this for this version of the spec.

**Comment by rinswind** [comment]
Manifests are hard to edit.
Even more so when in BND builds the manifest entirely from the code and there is nothing to edit.
I was hoping in fact to avoid the need to specify anything in the manifest and use only annotations for the application component.

**Comment by rotty3000** [comment]
Then why not simply write a meta-annotation which sets the proper values on the requirement?

I can show an example later...

**Comment by rotty3000** [comment]
I believe we've agreed that the CDI container id as configuration PID for Application Component was sufficient to configure the application. The one caveat to this is that there should be a way to specify the CDI container id.

**Comment by rinswind** [comment]
Correct
And we agreed that the CDI container ID can be specified as an attribute on the extender requirement:
```
Require-Capability: 
  osgi.extender;
  filter:="(&(osgi.extender=osgi.cdi)(version>=1.0)(!(version>=2.0)))";
  containerId="org.example.hello"
```
Or maybe `pid`
Or maybe `id`

I wonder how different is this from the original idea.

**Comment by rotty3000** [comment]
I've gone with:
```
Require-Capability: «
	osgi.extender; «
		filter:=”(&(osgi.extender=osgi.cdi)(version>=1.0)(!(version>=2.0)))”; «
		container.id="my.id"
```

**Comment by rotty3000** [comment]
closing, we can debate further on bugzilla if needed
