### ISSUE TITLE
[configuration] Should it be possible to gather @PID and @FactoryPID from super classes

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#36]
**Against**
- It is error prone to do this just like it is error prone to gather published service interfaces: #9 

**Suggestion**
- Don't do it.
- Specify the extender should log a warning.

**Comment by pkriens** [comment]
I think we already discussed we should not inherit annotations?

**Comment by rinswind** [comment]
I think we discussed on a case-by-case basis - and this is another case.

I am for us making the general decision that the extender will not search super classes for it's features.

I.e. CDI may search super classes (e.g. for the set of implemented interfaces) and we will work with that, but for any OSGi-specific work we will not search the super classes.

**Comment by pkriens** [comment]
agree

**Comment by rinswind** [comment]
Closing the issue with resolution:
No searching for any OSGi metadata in superclasses
