### ISSUE TITLE
[dto] Decide on the lifecycle/component split

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#38]
In the current DTOs there is:
- `LifecycleDTO` that handles all component configurations as a "package". When the package is resolved one or more `ComponentDTO` are created.
- ` ComponentDTO` has a list of concrete resolved configuration PIDs. All configurable elements (properties, target filters) are set and immutable. Change to configuration dependencies (an optional configuration appears) causes the re-creation DTO.

In @pkriens DTOs
- There is no `LifecycleDTO`.
- There is a lifecycle PID on `ComponentDTO`. I.e. the configurations are split into a primary one and additional ones.
- The configurable elements change in place as configurations come and go.

# LifecycleDTO
**For** 
- Consistent behavior: every layer of the DTOs has one type of dependency. When resolved it builds the next layer where this dependency type is set and immutable:
    - container has extensions and builds lifecycles
    - lifecycle has configurations and builds component
    - component has references and builds activations
    This resembles the original state machine.
**Against** `LifecycleDTO` model:
- May limit implementations
**Maybe**
- The nature of CDI may force the spec to require that the same levels are created/destroyed. Since there is no implementation freedom how/when to make them it makes sense for the DTOs to reflect this.

**Comment by rinswind** [comment]
I do not agree there must be a special lifecycle PID.
I prefer to treat all configurations as equal and have a `LifecycleDTO` that handles them. It is simply that we have one configuration (the factory one) with multiple cardinality. Then the `LifecycleDTO` has specific behavior on how to build configuration "packages" and create `ComponentDTO` for each one. This is symmetric with the references that also have cardinality and the `ComponentDTO` builds `ActivationDTOs` in a similar way.

**Comment by rotty3000** [comment]
The `ActivationDTO` to me is meaningless. I really have no idea what it's trying to do!

**Comment by rinswind** [comment]
The Application component can register multiple services.
- One can apply `@Service` to any `@ApplicationScoped` bean.
- One can apply `@Service` to any `ServiceFactory` and `PrototypeServiceFactory` 

So for the application component we have one more level of structure above component. For "standard" components at least for now there can be only one activation, which corresponds to the `@Component` bean. Also this follows the general DTO pattern that when one level is ready it creates the next level. So when the component is ready it creates it's activations.

At first `ActivationDTO` used to be `ServiceDTO`, but to include "immediate" beans I renamed it to `ActivationDTO` since they are created, but not registered as services.

For the record my initial architecture (with the per-component scopes) permitted the standard components to have many singleton service registrations just like the application component. There was near perfect symmetry between the two. I have real use cases for this, but I decided to stop pursuing them since I am in minority.

**Comment by rotty3000** [comment]
Could we instead go with 

`ComponentDTO` as the replacement for `LifecycleDTO`
AND
`ConfiguredComponentDTO` as the replacement for `ComponentDTO`?

This better reflects Peter's diagram and it also feels better. `Component` is more the abstraction embodied by our 3 component types: Application, Single, Factory. This explains very well.

I'd like this:
```
ContainerDTO {
	TemplateContainerDTO template;

	List<ExtensionDTO> extensions;

	ComponentDTO application;

	List<ComponentDTO> components;
}

ExtensionDTO {
	TemplateExtensionDTO template;
	Bundle extensionBundle;
}

ComponentDTO {
	TemplateComponentDTO template;

	// Application has 1
	// Single has 0..1
	// Factory has 0..N
	List<ConfiguredComponentDTO> configuredComponents;
}

ConfiguredComponentDTO {
	List<ConfigurationDTO> configurations;
	List<ReferenceDTO> references;

	// Application 0..N
	// Single & Factory 0..1
	List<ActivationDTO> services;
}

TemplateContainerDTO {
	String id;

	List<TemplateExtensionDTO> extensions;

	TemplateComponentDTO application;

	List<TemplateComponentDTO> components;
}

TemplateExtensionDTO {
	String name;
}

TemplateComponentDTO {
	String name;
	List<TemplateConfigurationDTO> configurations;
	List<TemplateReferenceDTO> references;
	List<TemplateActivationDTO> services;
}
```

**Comment by rinswind** [comment]
How about we use "instance" instead of "configured"?
1. Rename `ComponentDTO` -> `ComponentInstanceDTO`
2. Rename  `LifecycleDTO` -> `ComponentDTO`

Also I don't like having `Template` as a prefix because this implies that `TemplateComponentDTO` is a kind of component, which is not true. It is an object with very different structure that describes how a `ComponentDTO` is built. It's structure does not match that of `ConfiguredComponentDTO` either. Using prefixes in the names makes more sense when there is inheritance and therefore an "is a" relationship: `ConfiguredComponentDTO extends TemplateComponentDTO`. Peters model had inheritance, but the current model does not.  I use composition instead precisely because there is no suitable "is a" relationship.

Also why have a separate `ContainerDTO.application` field rather than one component of type `APPLICATION` in the common list? I have used a similar approach for factory configurations. There is no field for a factory configuration anywhere. Instead there is at most one `ConfigurationTemplateDTO` with  multiple cardinality in the `ComponentTemplateDTO.configurations`.

**Comment by rinswind** [comment]
I opened #47 for a discussion of another aspect where your suggestion differs from my dtos

**Comment by rotty3000** [comment]
I think we have agree to use the following terms:

- Rename `Component` -> `ComponentInstance`
- Rename `Lifecycle` -> `Component`
- use `ComponentTemplate`
- use `DependencyTemplate`

here is the diagram
![152-component-model](https://user-images.githubusercontent.com/146764/33779635-b87d41b6-dc1b-11e7-8c43-e3d7c80cdce7.png)

 attach DTO where appropriate

**Comment by rinswind** [comment]
The `Service` flavor of `Dependency Template` should be `Reference`
In the spec much like in the DS spec the distinction between providing services and consuming services must be obvious at all places. Hence the terminology - service to provide, reference to consume.

**Comment by rinswind** [comment]
I have changed the DTOs as suggested.

The discussion has changed direction to the abstract entities rather than the DTOs, which belongs either in bugzilla or in a different issue.

I am closing this issue
