### ISSUE TITLE
[configuration] Turn the "required" flag on @PID into an enum?

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#39]
**For**
- A boolean locks us into two options.
- Add an `enum ConfigurationPolicy { OPTIONAL, REQUIRED }`

**Against**
- We had such enums and removed them to simplify the API.

**Comment by rinswind** [comment]
Should we make it an internal class `enum PID.Policy { REQUIRED, OPTIONAL}`?

**Comment by rotty3000** [comment]
For me it's better since it can't be used elsewhere... and it means we don't have to "scope" the class name even more.

**Comment by rotty3000** [comment]
Done!

**Comment by rinswind** [comment]
In fact we have a third policy already: FACTORY

How about we remove `@FactoryPID` in favor of `@PID(value="org.example", policy=FACTORY)`?
It also is closer to DS even though to me catering to converts from DS is not a primary concern.
The PID and the policy are as tightly coupled as the `@Reference` `value` and `target`.

We already enforce the rule that no two PIDs can be the same between both `@PID` and `@FactoryPID`  in #27, so we already have rules that can't be expressed safely. We have to extend this that only one factory is allowed.

**Comment by rinswind** [comment]
One potential step further is:
`{OPTIONAL, REQUIRED, FACTORY}` is really `{OPTIONAL, MANDATORY, MULTIPLE}`.

So potentially
`@PID(value="org.example.factory", policy=MULTIPLE)`
or even
`@PID(value="org.example.factory", cardinality=MULTIPLE)`

The DTOs I have express factory configurations as a `ConfigurationDTO` dependency with multiple cardinality so this renaming fits them.

**Comment by rotty3000** [comment]
This eliminates the nice protection that repeatable vs. non-repeatable annotations gives.

**Comment by rotty3000** [comment]
also, it exposes the FACTORY policy (_or MULTIPLE cardinality_) to the _direct configuration injection_ scenario:

```
@PID(policy = FACTORY)
@Configuration
Config config;
```

**Comment by rinswind** [comment]
> also, it exposes the FACTORY policy (or MULTIPLE cardinality) to the direct configuration injection scenario
Ok I have to concede that we retain `@FactoryPID`
