### ISSUE TITLE
[References] Rename @Reference(servce=...) to @Reference(value=...)

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#4]
- **For**
    - Shorter code: `@Reference(Hello.class)` instead of `@Reference(service=Hello.class)`
-  **Against**
    - ?

**Comment by rotty3000** [comment]
Already done!

**Comment by rinswind** [comment]
Closing the issue

**Comment by rotty3000** [comment]
Since we are moving back the `@Filter` into `@Reference(target =...)` I think it makes sense to return to using `@Reference(service = ...)`. Thoughts?

**Comment by rinswind** [comment]
Why are we moving it back?
It was nice to have `@Service(<some classes>)` and a respective `@Reference(<some classes>)`

**Comment by rinswind** [comment]
Isn't `@Greedy` is applicable with `@Reference` too?
But we have it separate

**Comment by rotty3000** [comment]
A valid point! Should we just merge that also?

**Comment by rotty3000** [comment]
BUT with simply a boolean?

**Comment by rinswind** [comment]
BJ was against using booleans because they lock us to only two options.

So we may have to resurrect the `enum ReferencePolicyOption { GREEDY, RELUCTANT}` while at the same time not having an `enum ReferencePolicy`.

We are backtracking on the API design.
The general pattern I extracted was:
- We break all DS-like annotations until we get single-value ones
    - E.g. out of `@Reference` we extract `@Reference(<class>)`, `@PolicyOption(GREEDY | RELUCTANT)`
- For each single-value one with a limited set of values we break it into individual annotations
    - E.g. we break `@PolicyOption(GREEDY | RELUCTANT)` into `@Greedy` and `@Reluctant`
- We select defaults and remove the rest.
    - E.g. we choose reluctant as default, remove it and we are left with `@Greedy`

If we backtrack on `@Reference` and `@Greedy` what will happen with `@Bundle`, `@Prototype` which also are an "enum"?

We should stop at merging the filter back into `@Reference` with the argument that they are very tightly coupled or something of this sort.

Furthermore we use the "value(), but with other attributes" pattern on `@PID` so we might as well use it on `@Reference`

**Comment by rinswind** [comment]
I raised a similar issue for the `@PID.required()` #39

**Comment by rotty3000** [comment]
fine... let's make it an enum. I just can't see any future options. IT also means changing from `@Reference(greedy = true)` to super long `@Reference(policy = Policy.GREEDY)`

**Comment by rinswind** [comment]
What about `@Bundle` and `@Prototype`?
Merge them back into `Service.scope()` and `Reference.scope()`. And if so the entire idea of using `@Service` on type use sites breaks down.
We have to stop the backtrack at a reasonable phase.

**Comment by rotty3000** [comment]
Ok, so let's just stop at `@Reference(value, target)`!

**Comment by rotty3000** [comment]
Why do we need to continue to merge more in?

**Comment by rinswind** [comment]
To establish a pattern.

An API built from exceptions is not very nice to use. This is why I am for the `T, List<T>, Provider<List<T>>, ReferenceEvent<T>` solution.

But it seems a good enough balance.

**Comment by rotty3000** [comment]
FYI, I think there's logical reason to leave `@Greedy` separate. It doesn't apply to several `@Reference` scenarios as defined in #11  .

**Comment by rotty3000** [comment]
I'm closing this since I believe the work here is done!

**Comment by rinswind** [comment]
Agreed with the argument that `@Greedy` is separate because it doesn't apply everywhere `@Reference` does.
