### ISSUE TITLE
[dto][runtime] Clarify the ContainerDTO change count

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#40]
At present:
- `CdiRuntime.getContainerChangecount(Bundle)` returns the `service.changecount` of `CdiRuntime` at the 
time `ContainerDTO` of the passed `Bundle` last changed value.
- `ContainerDTO.changeCount` contains the same value, so that users can check if a DTO they may have is stale.

I am opening this issue to put this design up for review.

**Comment by rotty3000** [comment]
Are you sure it should not return the `Container`'s `service.changecount`? 

It doesn't make sense for `CdiRuntime.getContainerChangecount(Bundle)` to return the changecount of the runtime!

I think the behaviour expressed at the EEG was that the `CdiRuntime` service would have it's own `service.changecount`. And then that each `Container` (per bundle) would also have it's own `changecount` which would be obtainable by calling `CdiRuntime.getContainerChangecount(Bundle)` AND this value would be the same as that of the `ContainerDTO` SO that you would have something to compare against later! Otherwise, what's the point?

**Comment by rotty3000** [comment]
Consider the following example:
```
private final Bundle _bundle;

private volatile long _lastChange = 0;

@Inject
public CheckContainerUpdated(BundleContext bundleContext) {
	_bundle = bundleContext.getBundle();
}

/*
 * This event only tells us that the CdiRuntime has changed (since
 * `service.changecount` causes this to be an update)
 */
void updates(@Observes AddingEvent<CdiRuntime> event) {
	event.onUpdate(this::check);
}

private void check(CdiRuntime r) {
	if (_lastChange < r.getContainerChangeCount(_bundle)) {
		ContainerDTO containerDTO = r.getContainerDTO(_bundle);

		_lastChange = containerDTO.changeCount;

		reportChanges(containerDTO);
	}
}

private void reportChanges(ContainerDTO containerDTO) {
	// ...
}
```

I have one caveat with the above example and with the `getContainerChangecount(Bundle)` method in general, and that is that between calling it, and then calling the `getContainerDTO(Bundle)` the result might actually have changed.

However, the cost of generating all the DTOs might be high. Is the risk worth taking?

**Comment by rinswind** [comment]
> Are you sure it should not return the Container's service.changecount?
But it does.

`CdiRuntime` `service.changecount` increases only in response to a change in some container.
That container has a private` changecount` field that takes a snapshot of the global `service.changecount+1`. That snapshot remains unchanged until the same Container causes the global `service.changecount` to increase again.

I.e. each Container has a private `changecount` that does not increase by 1, but still increases only when the container has changed. The users can relate the container `changecount` to the global `service.changecount`. For the container changecount all that matters is that it has increased since the last time you have seen it. The difference does not have to represent the number of changes.

Thinking of this now I am not sure this is right. Maybe we should not specify any relation. Just that when a container changes state it must increase the global counter and the local counter - don't even say by how much.

**Comment by rinswind** [comment]
> However, the cost of generating all the DTOs might be high. Is the risk worth taking?

I added the light method `getContainerChangecount()` precisely because I did not want to force the spec implementors to provide cheap DTOs (i.e. maintain a cache). Also Tim Ward suggested that we add such a method so I didn't give it another thought.

On the other hand
- The users can always abuse the API and only go to the `CdiRuntime.getContainerDTO()`
- All we can do is document that the `CdiRuntime.getContainerChangecount()` is cheap.
- The DS `ServiceComponentRuntime` also has a global changecount, but no local changecounts. It seems to force the users to get the DTOs they care about and do a deep-equals. Probably by implication the DTOs must be cheap to get.

So do we trust the authors of the DS API and go their way or should we raise the issue that DS should not force cheap DTOs?

**Comment by rotty3000** [comment]
>Thinking of this now I am not sure this is right. Maybe we should not specify any relation. Just that when a container changes state it must increase the global counter and the local counter - don't even say by how much.
I agree with this! I think they should be unrelated. This way there's no need to even "get" the `service.changecount` from `CdiRuntime` as my example demonstrates. The change in that value is ONLY used to trigger the "update" event subsequently used to perform a "container specific" changecount comparison.

Thoughts?

**Comment by rinswind** [comment]
Agreed that the global/local change counts are unrelated.

> This way there's no need to even "get" the service.changecount from CdiRuntime as my example demonstrates.

This is a separate decision I think? About the cost of making DTOs? If someone wants to track a particular container and there is no cheap way to get the changecount (i.e. CdiRuntime.getContainerChangecout()`), they have to get the entire `ContainerDTO` and check `ContainerDTO#changecount`

**Comment by rotty3000** [comment]
When you try to relate the values to each other you imply that there's value at some time to compare them for some purpose. What I'm saying is that there's never a good reason to do that, thus they should not be related in any way.

**Comment by rotty3000** [comment]
otherwise, I think we are in agreement!

**Comment by rinswind** [comment]
The `CdiRuntime.getContainerChangecount(Bundle container)` returns a value for `ContainerDTO#changecout`. I already agreed that this value will not have relation to the global changecount.

The reason to do that is that a user can retain the last `ContainerDTO#changecount` of the bundle thay track and cheaply discover that it has changed by calling the `CdiRuntime.getContainerChangecount(my container bundle)`, rather than having to build an entire ContainerDTO only to check if it has the same `ContainerDTO#changecount` and throw it away

**Comment by rotty3000** [comment]
that's exactly what my exampled demonstrated...

**Comment by rinswind** [comment]
Ok so
- If we decide `ContainerDTO` is cheap: remove `CdiRuntime.getContainerChangecount()`
- If we decide `ContainerDTO` is expensive: remove `ContainerDTO#changecount`

**Comment by rotty3000** [comment]
now we're getting somewhere :)

> If we decide ContainerDTO is expensive: remove ContainerDTO#changecount

I would go for this option.

**Comment by rotty3000** [comment]
in fact I'm not even sure it's necessary to remove the `ContainerDTO.changeCount` so I am leaving it for now.

I've updated the javadoc

**Comment by rinswind** [comment]
Agreed.
The changecount is an integral part of the DTO since it orders the DTOs in time. Useful to compare DTOs.
I was only trying to address your concerns that the user may be confused the changecount has increased by the time they get the DTO.
