### ISSUE TITLE
[events] Fire sync or async events?

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#42]
[Observers must say what they handle](http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#observes)
[And they can't receive the other type](http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#observer_resolution)

# Suggestion
- Fire sync events since we should retain the semantics of `org.osgi.framework.ServiceListener`.
- Retain the semantics of DS too. I think it calls the dynamic binders synchronously?

**Comment by rotty3000** [comment]
agreed!

**Comment by rotty3000** [comment]
updated javadoc
