### ISSUE TITLE
[references] Define reference name generation rules

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#44]
I was able to implement this:

For `prefix`:
1. If `@Named` is present
    - `prefix=<named value>`
2. else
    - `prefix=<name of raw base type>`, which is the super class.

For `suffix`:
1. If injection point is a field
    - `suffix=field name`
2. else if injection point is a constructor
   - `suffix="new"`, can't collide with any method.
3. else if injection point is a 1 parameter method
    3a. If method name starts with "set"
        - `suffix=method name - "set"`
    3b. else 
        - `suffix=method name`
4. else 
    - `suffix=method name + "." + parameter position`

For `name`:
`name = prefix.toLowerCase() + "." + suffix.toLowerCase()`

The properties:
`target=name + ".target"`
`cardinality=name + ".cardinality"`

# Issues
- I am not converting camel case to dot-separated strings
- Can we use the converter somehow?
- What to do if the bean base type is excluded from participation in dependency injection with `@Typed`.  Probably do nothing. The user needs to relate code to configuration  - anything else is too confusing.

**Comment by rotty3000** [comment]
Agreed!

**Comment by rinswind** [comment]
Does this mean that:
- I am not converting camel case to dot-separated strings: is okay?
```
package org.example;
  
@Component
class Foo {
    // target = org.example.foo.initandcallbar.target
    // cardinality = org.example.foo.initandcallbar.cardinality
    @Inject 
    void initAndCallBar(@Reference Bar bar) {
    }
}
```
- Can we use the converter somehow?
We will not use the converter to make camel case to dot separated (if it can do this)

**Comment by rotty3000** [comment]
I don't think we need to convert camel case of member names, if anything we should keep the names because of the variety of members to consider. I would not even alter the member names and simply append param index to the member name in case of constructor or method.

**Comment by rinswind** [comment]
This raises the question whether we should use member names "as is" however ugly this may look.

In this way the java compiler guarantees we can't hit conflicts. E.g. `setfoo` vs  `setFoo` or `initAndCallbar` vs `initAndCallBar`.

Also it doesn't seem to be an option for us to beautify the names and raise errors if there is a conflict because for legacy apps the code may be hard to change.

**Comment by rotty3000** [comment]
This is the production I'm recommending in the spec right now:
```
name   ::= prefix '.' suffix
prefix ::= named | qname
named  ::= < value of @Named annotation >
suffix ::= field | ctor | method
field  ::= < name of field >
ctor   ::= 'new' pIndex
method ::= mName pIndex
mName  ::= < method name >
pIndex ::= < index of @Reference parameter >
```

no mention of changing the member names at all.

what do you think?

**Comment by rotty3000** [comment]
`qname` is already defined in the core spec.

**Comment by rinswind** [comment]
This looks good enough.
We can close the issue.
