### ISSUE TITLE
[services] How to handle @Typed on managed beans?

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#45]
#Issue
[@Typed on beans limits the Bean.getTypes()](http://docs.jboss.org/cdi/api/2.0/javax/enterprise/inject/Typed.html)

So
- On one hand we have `@Service` including `@Service(Foo.class, Bar.class)`
    - Applies to bean, producer field, producer method, type use
- On the other hand we have `@Typed(Foo.class, Bar.class)`
    - Applies to bean, producer field, producer method

# Suggestion
Somehow both should be used.
`@Typed` is used internally for dependency injection etc.
`@Service` is used externally.
So I may want to inject the bean under one set of types, but publish it under another. Maybe define that `@Service` must be a subset of `@Typed`

**Comment by rotty3000** [comment]
I agree that `@Service` should be a subset of `@Typed` because otherwise we break potential ability to proxy w.r.t. Decorators and Interceptors which both honour `@Typed`.

**Comment by rinswind** [comment]
Interceptors/Decorators was what I had in mind too.
So we can resolve this as proposed?

**Comment by rotty3000** [comment]
Agreed!

**Comment by rinswind** [comment]
Marking for description somewhere (javadoc/spec)

**Comment by rotty3000** [comment]
I've added the following text to the spec:
```
	<section>
		<title>Managed bean types and service types</title>

		<para>Service types must be a subset of managed bean
		types, including constraints on bean types declared by the CDI
		<code>@javax.enterprise.inject.Typed</code> annotation. This is so that
		CDI features like <emphasis>Decorators</emphasis> and
		<emphasis>Interceptors</emphasis> are supported.</para>
	</section>
```

**Comment by rinswind** [comment]
Make it more formal:
"This restriction is required to support CDI features like <emphasis>Decorators</emphasis> and		<emphasis>Interceptors</emphasis>"

As a side note we have to test how decorators/interceptors actually work

**Comment by rotty3000** [comment]
new text:
```
	<section>
		<title>Managed bean types and service types</title>

		<para>Service types must be a subset of managed bean
		types, including constraints on bean types declared by the CDI
		<code>@javax.enterprise.inject.Typed</code> annotation. This restriction
		is required to support CDI features like <emphasis>Decorators</emphasis>
		and <emphasis>Interceptors</emphasis>.</para>
	</section>
```

**Comment by rinswind** [comment]
Good enough.
Let's close the issue.
