### ISSUE TITLE
[dto] How to represent aggregations?

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#48]
# Current state
- Use only List and Map for aggregations - never use arrays
- Never have null values for aggregation fields. Use empty collections instead.

# Suggestion
Retain current state

**Comment by rotty3000** [comment]
I would use List.

I don't know why we would use maps, unless for configuration properties.

**Comment by rinswind** [comment]
Maps are only used in two places:
- In the template set for the default properties
- In the runtime set for the resolved properties.

Closing the issue: the API on `rauge/cdi-spec` is fixed to consistently use lists/maps
