### ISSUE TITLE
[services][references] Decorators and Interceptors

### ISSUE THREAD

**Issue by rotty3000** [pkriens/cdi#49]
They are effectively just handled by proxies around the actual instance returned from the bean. 

Of course it's possible to try to proxy a type which is not proxyable, which is why `@Typed` was invented to reduce the set of bean types. So, as long as we support @Typed reducing our list of service types, and provided those types are proxyable (i.e. interfaces or easy to construct classes) then Decorators and Interceptors can be used.

- For published services: this means that we can wrap services in proxies because our "service instances" are created by beans in CDI.
- For references: we can ONLY proxy the value returned from the synthetic bean which might be any of the views supported, or containers, and not every single service instance. If you need a proxy around an instance, then you probably want to use `ReferenceEvent` or single service reference injection mode.

**Comment by rotty3000** [comment]
I have one doubt about the reference scenario.

typically decorators and interceptors are applied to the instances returned from beans. However, in the case of our synthetic reference beans proxying the bean type makes little sense due to the fact that often these are containers of some form.

I was wondering if we should therefore apply the proxies on the service instances. The interesting thing here is that there are at most two types to proxy; 
1) the service type declared by the injection point representation AND 
2) the type defined on `@Reference(value)`

**Comment by rinswind** [comment]
We need to use the SPI to make decorated+intercepted objects.
I think the SPI only allows beans to be decorated+intercepted. The method likely is `BeanManager.getReference(Bean<?> bean, Type beanType, CreationalContext<?> ctx)`.

Therefore to proxy the entries of containers like `Provider<T>`, `List<T>`, `Optional<T>` we must have a bean `T` which the synthetic bean `Provider<T>` can call internally. Can we potentially hit ambiguity errors if we always have the `T` bean for every representation of every service?
