### ISSUE TITLE
[DTO] use `List<>` for ComponentDTO, ComponentTemplateDTO

### ISSUE THREAD

**Issue by rotty3000** [pkriens/cdi#50]
When aggregating Component DTOs they should be in a `List<>`.

- the first list entry represents the application
- every other entry represents the single|factory components
- on the static|template side the list is fixed size, describing each and every component
- on the runtime side the list has `size=1` until the application is resolved
- once the application is resolved the list `size=<static|template>.size`

**Comment by rinswind** [comment]
Agreed
