### ISSUE TITLE
[References] What does @Reference Collection<T> mean?

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#6]
- In DS
    - The user can declare a non-final `Collection<T>`/`List<T>` field = null
        - DS will supply it's collection implementation and update it on subsequent changes
    - The user can declare a final `<T extends Collection> T` field and initialize it
        - DS will update the user collection object on subsequent changes
- **Suggestion**
    - Support any `<T extends Collection<S>>` with a default constructor:
        `@Reference @Inject CopyOnWriteArrayList<Hello> hello;`
    - The extender will
        1. The type is assignable from `Collection`
        2. The type is a *concrete class*
        3. The type has a default constructor
    - If so the extender will make a synthetic bean that has that type
    - The bean will make the collection using the default constructor from Bean<T>.create()
    - The extender will then add/remove to/from the collection.
    - If the type is the *interface* `List<s>` provide a concurrent collection ordered by the natural service order

**Comment by rinswind** [comment]
On the EEG f2f it was proposed that the users should not be able to require their own collection types.
Probably injections of `<C super List<T>>`  will be supported where `List<T>` is immutable as per #11

**Comment by rotty3000** [comment]
Didn't we agree that
`@Reference Collection<S> col;`
was static, and
`@Reference Producer<Collection<S>> col;`
was dynamic?

**Comment by rotty3000** [comment]
yes, I see that we did...

So are we saying that we should still support both interfaces `Collection` and `List`?

**Comment by rinswind** [comment]
I tried to leave some flexibility because you and @pkriens wanted much more. So I don't insist on this.
May help with migration
At present `<C super List<T>>={List<T>, Collection<T>, Iterable<T>} `

**Comment by rotty3000** [comment]
I'm ok with not having MORE flexibility than `<C super List<T>>={List<T>, Collection<T>, Iterable<T>}`.

In fact in pure CDI terms, the `Bean.getTypes()` of a `Bean<List<T>>` would include `List<T>, Collection<T>, Iterable<T>`.

**Comment by rotty3000** [comment]
For the sake of speed I'm going to take a unilateral decision and say that `List, Collection, Iterable` is good for the first release.

**Comment by rinswind** [comment]
Agreed
