### ISSUE TITLE
[Services] Add escape hatch for published service types

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#7]
- **For**
    - Symmetry with `@Reference`
    - Just as important as on `@Reference` to be able to set exactly what you want when convenience forms fail.
        - E.g. publish under the super-super class
- **Suggestion**
    - `@Service(Test.class)`
    - Invalid to set value when annotating interface type use and/or super class type use

**Comment by rotty3000** [comment]
I'm not sure I get the suggestion... Can you clarify?

**Comment by rinswind** [comment]
The escape hatch is to add 
```
@interface Service {
    Class<?>[] value() default Object.class;
}
```
Without the escape hatch it is impossible to publish under `Base` and verbose to publish under `Service`.
```
class Base {
}

class RicherBase extends Base implements Service {
}

@Service({Base.class, Service.class})
class ServiceImpl extends RicherBase {
}
```
Without the escape hatch it is impossible to limit the published interfaces when using producers:
```
public ServiceImpl implements ServiceOne, ServiceTwo, Internal {
}

@Produces  @Component @Service({ServiceOne.class, ServiceTwo.class})
public ServiceImpl createServiceImpl() {
    return new HelloImpl(formatter);
}
```
This has to be illegal
```
public ServiceImpl extends RicherBase implements @Service(RicherBase.class) Service {
}
```
We should discuss if this should be legal...
```
@Service(MessagFormatter.class)
public SimpleHello extends AbstractHello implements @Service Hello {
}
```
... or we force either a class list in `@Service` or empty `@Service` on `TYPE_USE` sites, but not both.

**Comment by rotty3000** [comment]
Let's discuss this because I largely disagree.

BTW, it's not verbose to publish the example under `Service` ... that's the default! `Any implemented interfaces`!

So this would suffice:
```
@Service
class ServiceImpl extends RicherBase {
}
```

**Comment by rinswind** [comment]
I want to publish under **exactly** `Base` and `Service`. Not under all implemented interfaces.

I can't select `Base` at all since it is the super class of my super class.
And to select `Service` I must repeat the `implements Service` in order to expose a site where I can add `@Service`
```
class ServiceImpl extends RicherBase implements @Service Service {
}
```

More importantly I need the producers to work.

**Comment by rinswind** [comment]
On the EEG F2F we decided for the escape hatch
So it will be added to the spec.
Closing the issue
