### ISSUE TITLE
[Services] Allow @Service on the super class?

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#8]
```
class Hello extends @Service Greeter {
    ...
}
```
- **For**
    - Seems natural and may be needed
- **Against**
    - Providing an `@Service({.. the classes ...})` escape hatch is sufficient
- **Suggestion**
    - Make it mandatory to set `@Service` there to export under the super class
    - Forbid `@Service` there if `@Service` used on `@Component` and retain the default resolution

**Comment by pkriens** [comment]
I am not sure I see the problem?

**Comment by rinswind** [comment]
I may want to do this:
```
class Foo extends @Service FooBase implements @Service FooService, FooInternal {
}
```
Also if we have default rules when to pick the super class and when the interfaces, and then explicit support to pick individual interfaces it seems natural to have a way to explicitly pick the super class.

**Comment by pkriens** [comment]
And you can't do that now? the @Service can be applied to the superclass?

**Comment by rinswind** [comment]
We had not specified `@Service` can go on the super class.
On the EEG F2F we decided it makes sense to do so.
Closing the issue

**Comment by rotty3000** [comment]
@rinswind in fact didn't we decide against this in the end???

**Comment by rinswind** [comment]
I don't think so. We decided against exhaustive scans of the class hierarchy.
I did re-cap all about `@Service` at some point and no one objected on having it on `extends` as well.
But then again you were able to hear better...

**Comment by rotty3000** [comment]
Wait... your last comment is confusing. This issue is about having @Service on super classes... NOT about having @Service on `extends` (which is just another type_use scenario).

What I want to clarify is that we are NOT scanning the class hierarchy for @Service, that we are ONLY considering @Service directly on a bean class (producer method).

**Comment by rinswind** [comment]
My mistake.
What you have written is what we agreed on.

**Comment by rinswind** [comment]
Actually #9 is about scanning up the hierarchy.
This one is about having `extends @Service`
In all cases both are resolved as @rotty3000 describes.
