### ISSUE TITLE
[Services] Scan super classes for @Service

### ISSUE THREAD

**Issue by rinswind** [pkriens/cdi#9]
- **For**
    - More flexibility
- **Against**
    - Can cause unintended publication if changes made to the super class.
    - Providing an `@Service({.. the classes ...})` escape hatch is sufficient
- **Suggestion**
    - Don't do it

**Comment by pkriens** [comment]
It is trivial to add interfaces to the class declaration and it would be impossible to remove a service from a super class if desired. So I think this is a pretty clear **don't**.

**Comment by rinswind** [comment]
I agree.

**Comment by rinswind** [comment]
The EEG agrees that we don't do this as well
Closing
